build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Reflection 70B
python_version: py39
requirements: []
resources:
  accelerator: A100:4
  cpu: '1'
  memory: 24Gi
  use_gpu: true
secrets:
  hf_access_token: set token in baseten workspace
system_packages: []
trt_llm:
  build:
    base_model: llama
    checkpoint_repository:
      repo: mattshumer/Reflection-Llama-3.1-70B
      source: HF
    max_batch_size: 32
    max_beam_width: 1
    max_input_len: 7168
    max_output_len: 1024 # 4096
    num_builder_gpus: 4
    quantization_type: no_quant
    tensor_parallel_count: 4
